version: '3'
services:
  db:
      image: postgres:14.4-alpine
      container_name: db
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:5432

  jaeger:
      image: jaegertracing/all-in-one:latest
      ports:
        - "6831:6831/udp"
        - "16686:16686"
        - "14268:14268"
      environment:
       COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
       - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
       - "4317:4317"
       - "4318:4318"
  garantex:
    build: .
    container_name: garantex_service
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
     - ./.env:/test_garantex/.env
     - ./${DB_MIGRATIONS_DIR}:/test_garantex/${DB_MIGRATIONS_DIR}