version: '3'
services:
  db:
      image: postgres:14.4-alpine
      container_name: db
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - 5432:5432