version: '3'
services:
  db:
      image: postgres:14.4-alpine
      container_name: db
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - ${DB_PORT}:5432

  jaeger:
      image: jaegertracing/all-in-one:1.48
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686" # UI
        - "14268:14268"
        - "9411:9411"
  garantex:
    build: .
    container_name: garantex_service
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    volumes:
     - ./.env:/test_garantex/.env
     - ./${DB_MIGRATIONS_DIR}:/test_garantex/${DB_MIGRATIONS_DIR}